### ISSUE TITLE
Car-net seems discontinued

### ISSUE THREAD

**Issue by ottoba** [thomasesmith/vw-car-net-api#4]
I tried this unsuccessfully. The first step went ok, but at the second step, I could only get 500s or 404s back. More worryingly, what seems to be the official website entry also doesn't work. This URL returns an actual form: https://identity.na.vwgroup.io/signin-service/v1/b680e751-7e1f-4008-8ec1-3a528183d215@apps_vw-dilab_com/login/authenticate?relayState=[YOURRELAYSTATE] But after this, it either does nothing or returns a nondescriptive error.

My guess is that car-net is discontinued? Would love to hear people's experiences!

**Comment by andig** [comment]
Not sure, however the "new" VW login flow has been discovered, see https://github.com/davidgiga1993/AudiAPI/issues/13 for the related Audi discussion

**Comment by thomasesmith** [comment]
@ottoba If you tried unsuccessfully, we can figure out why, but I really don't think the cause is that Car-Net is discontinued. I am able to log in fine using their iOS app, their web app, and most importantly with the app I've written that uses all the steps outlined in this repo. The authentication steps still work as expected. All the tests I've written for this are still passing. VW Car-Net as a service is alive and well. 

@ottoba Are you outside of North America? I have only tested this with my U.S.A. Car-Net account and I don't know how it will respond when attempting to use this method to log in to accounts outside of that region.

**Comment by thomasesmith** [comment]
I closed this Issue because it's not describing a problem with the repo and is more describing a problem with your own implementation. But please feel free to continue to comment in here if you like, @ottoba, so we can figure out what is going wrong for you.

**Comment by ottoba** [comment]
Hi Thomas, thanks for the replies and your documentation. I'm located in The Netherlands. I guess I hypothesized too soon that the problem was in car-net, since your repo is still working in your app. Anyway, any help would be greatly appreciated. In step 2, I'm not sure which URL to use. First, I tried the literal address from the manual, "signin-service/v1/b680e751-7e1f-4008-8cc1-3a528183d215@apps_vw-dilab_com/login/identifier", with and without parameters. I got only errors, and after changing the URL to obvious nonsense, I got the same errors, so I concluded that the URL was probably wrong. Then I changed it to "https://identity.na.vwgroup.io/signin-service/v1/b680e751-7e1f-4008-8cc1-3a528183d215@apps_vw-dilab_com/login/identifier", and still got errors but at least coming from the server.

As a first step, could you say which one of the approaches should be correct?

Thanks again!

**Comment by andig** [comment]
Check out the native api in https://github.com/trocotronic/weconnect. I‘ve ir searching through github, not sure why it‘s so unknown...

**Comment by ottoba** [comment]
Thanks andig! Turns out that there are several implementations around for VW APIs:

https://github.com/wez3/volkswagen-carnet-client
https://github.com/robinostlund/volkswagencarnet
https://github.com/reneboer/python-carnet-client

But I personally used the one you recommended and added a missing feature to it, and it works now! Thomas, thanks for your work too, it contained useful hints without which I could not have added the feature I needed :)

**Comment by andig** [comment]
> Turns out that there are several implementations around for VW APIs:

@ottoba while that's true imho the one I've linked is the only one that has the new VW ID login flow implemented what also Audi is using today. So that's the best reference to the modern version of the API (though I've lost track how they call all these...)

> But I personally used the one you recommended and added a missing feature to it, and it works now!

Would be great to PR them back to the original site to let others participate ;)

**update** haha, noticed you did that, thank you! As you're interested in controlling the car's charging apparently I'd like to selfishly recommend https://github.com/andig/evcc which has bells any whistles for any wallbox or car api.

**Comment by ottoba** [comment]
Thanks @andig for the tip, seems like a nice program that you built! I'm doing something similar but then by adjusting the charging on the car, instead of on the charging point.. I also ran a start-up which built a software-only smart charging solution, laadje.nl. Perhaps we could cooperate at some point :)

**Comment by andig** [comment]
Sure, feel free to get in contact at cpuidle@gmx.de any time.
